spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5438/aurora_db?sslmode=disable&stringtype=unspecified
    username: aurora_user
    password: aurora_password
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 5000 # 5 seconds
      max-lifetime: 580000 # 9 minutes 40 seconds
      data-source-properties:
        loginTimeout: 5 # 5 seconds
        socketTimeout: 30 # 30 seconds
        ApplicationName: polaris

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  sql:
    init:
      schema-locations: classpath:aurora-schema.sql
      mode: always
      platform: postgresql

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
