#
# Copyright 2016 Netflix, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

version: "2"

services:
    metacat:
        image: netflix_metacat_test/metacat_server:latest
        links:
            - hive-metastore
            - hive-metastore-db
            - s3-mysql-db
            - mysql-57-db
            - mysql-56-db
            - mysql-55-db
            - usermetadata-db
        ports:
            - '8080'
            - '8000'
            - '12001'
            - '12002'
        volumes:
            - ./build/logs/metacat:/usr/local/tomcat/logs
            - ./etc-metacat:/etc/metacat:ro
        environment:
            VIRTUAL_HOST: metacat.docker
            TOMCAT_OPTS: -Dlog4j.configuration=metacat-functional-test.log4j.properties
            JAVA_OPTS: '-ea
                -Xmx2G
                -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
                -noverify
                -Dnetflix.environment=test
                -Dnetflix.discovery.registration.enabled=false
                -Dnetflix.appinfo.validateInstanceId=false
                -Dnetflix.appinfo.vipAddress=
                -Dnetflix.appinfo.metadata.route53NamePrefix=
                -Dnetflix.appinfo.metadata.enableRoute53=false
                -Dmetacat.elacticsearch.cluster.name=
                -Dmetacat.plugin.config.location=/etc/metacat/catalog
                -Dmetacat.usermetadata.config.location=/etc/metacat/usermetadata.properties'
        labels:
          - "com.netflix.metacat.oss.test"
          - "com.netflix.metacat.oss.test.war"
    usermetadata-db:
        image: mysql:5.5
        volumes:
            - ./sql/usermetadata/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
        environment:
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_USER=metacat_user
            - MYSQL_PASSWORD=metacat_user_password
            - MYSQL_DATABASE=metacat
        labels:
          - "com.netflix.metacat.oss.test"
    mysql-55-db:
        image: mysql:5.5
        volumes:
            - ./sql/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_USER=metacat_user
            - MYSQL_PASSWORD=metacat_user_password
            - MYSQL_DATABASE=test
        labels:
          - "com.netflix.metacat.oss.test"
    mysql-56-db:
        image: mysql:5.6
        volumes:
            - ./sql/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_USER=metacat_user
            - MYSQL_PASSWORD=metacat_user_password
            - MYSQL_DATABASE=test
        labels:
          - "com.netflix.metacat.oss.test"
    mysql-57-db:
        image: mysql:5.7
        volumes:
            - ./sql/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_USER=metacat_user
            - MYSQL_PASSWORD=metacat_user_password
            - MYSQL_DATABASE=test
        labels:
          - "com.netflix.metacat.oss.test"
    s3-mysql-db:
        image: mysql:5.6
        volumes:
            - ./sql/s3-mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_USER=metacat_user
            - MYSQL_PASSWORD=metacat_user_password
            - MYSQL_DATABASE=metacat
        labels:
          - "com.netflix.metacat.oss.test"
    hive-metastore:
        image: danielbwatson/metacat-test-hive-metastore:1.0.0
        links:
            - hive-metastore-db
        ports:
            - '9083'
            - '8000'
        environment:
            - HIVE_METASTORE_HADOOP_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
        labels:
          - "com.netflix.metacat.oss.test"
          - "com.netflix.metacat.oss.test.hive"
    hive-metastore-db:
        image: mysql:5.6
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_USER=metacat_user
            - MYSQL_PASSWORD=metacat_user_password
            - MYSQL_DATABASE=hive
        labels:
          - "com.netflix.metacat.oss.test"
    storage-barrier:
        #image: ddn0/wait:latest
        image: martin/wait:latest
        links:
            - hive-metastore-db
            - s3-mysql-db
            - mysql-57-db
            - mysql-56-db
            - mysql-55-db
            - usermetadata-db
        environment:
            - TARGETS=hive-metastore-db:3306
            - TARGETS=s3-mysql-db:3306
            - TARGETS=mysql-57-db:3306
            - TARGETS=mysql-56-db:3306
            - TARGETS=mysql-55-db:3306
            - TARGETS=usermetadata-db:3306
        labels:
          - "com.netflix.metacat.oss.test"
    service-barrier:
        #image: ddn0/wait:latest
        image: martin/wait:latest
        links:
            - hive-metastore
        environment:
            - TARGETS=hive-metastore:9083
        labels:
          - "com.netflix.metacat.oss.test"
    metacat-barrier:
        #image: ddn0/wait:latest
        image: martin/wait:latest
        links:
            - metacat
        environment:
            - TARGETS=metacat:8080
            - TARGETS=metacat:12001
            - TARGETS=metacat:12002
        labels:
          - "com.netflix.metacat.oss.test"
    # postgres-host-84:
    #     image: postgres:8.4
    #     volumes:
    #         - ./sql/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    #     environment:
    #         - POSTGRES_PASSWORD=postgres_host_password
    #         - POSTGRES_USER=metacat_user
    #         - POSTGRES_DB=test
    #     labels:
    #       - "com.netflix.metacat.oss.test"
